# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  one:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: "echo Greetinngs and Salutations"
  two:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  one_and_two:
    jobs:
      - one
