version: 2.1

jobs:
  one:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Greetinngs and Salutations"
      - run: sleep 25
      
  two:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "A more familiar Hi"
      - run: sleep 15
          


workflows:
  one_and_two:
    jobs:
      - one
      - two

