version: 2.1

jobs:
  one:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: "echo Greetinngs and Salutations"
      - run: sleep 25
  two:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: "echo A more familiar Hi"
      - run: sleep 15

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  one_and_two:
    jobs:
      - one
      - two
